project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - slides/session1.qmd
    - slides/session2.qmd
    - slides/session3.qmd
    - slides/session4.qmd
    - slides/session5.qmd
    - slides/session6.qmd
    - slides/session7.qmd
    - slides/session8.qmd
    - slides/intro-video.qmd
  resources:
    - CNAME
    - .nojekyll
    - slides/pdf/*.pdf

website:
  title: ""
  search: false
  navbar:
    search: false
    title: "BI to AI"
    right:
      - href: slides.qmd
        text: Slides
      - text: AI Lab
        href: https://ai-lab.rice-business.org
        target: _blank
      - text: XYZ Corp
        href: https://xyzcorp.rice-business.org
        target: _blank

format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
